version: "3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 21
      MYSQL_DATABASE: forum
    volumes:
      - "./docker/volume_mysql:/var/lib/mysql"
    networks:
      - spring
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    networks:
      - spring

  forum:
    build:
      context: ./
      dockerfile: ./forum/Dockerfile
    image: forum
    networks:
      - spring
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - "./forum:/home"
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    depends_on:
        - db
        - adminer
    command: ["mvn", "spring-boot:run"]
networks:
  spring:
    driver: bridge
